module.exports = [
  {
    name: "Engagement Ring",
    img: "",
    price: "$1,399.99",
    type: "ring",
    size: "size 8",
    material: "14k gold",
    stones: "diamond",
    weight: "2.05g",
  },
  {
    name: "Gold Charm Bracelet",
    img: "",
    price: "$1,399.99",
    type: "bracelet",
    size: "19.75cm",
    material: "18k gold",
    stones: "diamonds",
    weight: "60.95g",
  },

  {
    name: "Gold Bracelet",
    img: "",
    price: "$2,499.99",
    type: "bracelet",
    size: "19.75cm",
    material: "18k gold",
    stones: "na",
    weight: "18.6g",
  },
  {
    name: "Gold Diamond Bracelet",
    img: "",
    price: "$3,999.99",
    type: "bracelet",
    size: "17.75cm",
    material: "14k gold",
    stones: "diamonds",
    weight: "13.35g",
  },
  {
    name: "Gold Cuban Link Chain",
    img: "",
    price: "$6,999.99",
    type: "necklace",
    size: "22in",
    material: "14k gold",
    stones: "na",
    weight: "79g",
  },
  {
    name: "Tiffany & Co. Silver Charm Bracelet",
    img: "",
    price: "$399.99",
    type: "bracelet",
    size: "7in",
    material: "925 silver",
    stones: "na",
    weight: "25.3g",
  },
  {
    name: "Aztec Pendant Necklace",
    img: "",
    price: "$599.99",
    type: "necklace",
    size: "24in",
    material: "925 silver",
    stones: "na",
    weight: "59.5g",
  },
];
